name: chat_app_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.3
  animated_splash_screen: ^1.3.0
  double_back_to_close_app: ^2.1.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  permission_handler: ^10.4.5
  intl: ^0.17.0
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - images/

